/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Dados.Csv;
import HorarioManager.UtilidadesHorario;
import static Interfaces.Home.caminho;
import com.opencsv.exceptions.CsvException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static msg.mensagemauto.AdminForever.posMensagem;
import msg.mensagemauto.UtillMsg;

/**
 *
 * @author Mandelli
 */
public class SetMsgs extends javax.swing.JFrame {
    public static boolean editando = false;
    public static int indexMsg;
    public List<String[]> dados = Telas.select.dados;
    public int posMensagem = 0;
    public int posPessoa = 1;
    public int posHorario = 2;
    public int posWeek = 3;
    /**
     * Creates new form SetMsgs
     */
    public SetMsgs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mensagem = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        pessoa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        minuto = new javax.swing.JTextField();
        seg = new javax.swing.JCheckBox();
        ter = new javax.swing.JCheckBox();
        qua = new javax.swing.JCheckBox();
        qui = new javax.swing.JCheckBox();
        sex = new javax.swing.JCheckBox();
        sab = new javax.swing.JCheckBox();
        dom = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        mensagem.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        mensagem.setText("digite aqui a sua mensagem");
        mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensagemActionPerformed(evt);
            }
        });

        hora.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        hora.setText("HH");

        pessoa.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        pessoa.setText("jão");

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mensagem:");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horario:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Para quem?");

        confirmar.setBackground(new java.awt.Color(51, 51, 51));
        confirmar.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 255, 255));
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(51, 51, 51));
        cancelar.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(":");

        minuto.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        minuto.setText("MM");

        seg.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        seg.setForeground(new java.awt.Color(255, 255, 255));
        seg.setText("Seg");
        seg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segActionPerformed(evt);
            }
        });

        ter.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        ter.setForeground(new java.awt.Color(255, 255, 255));
        ter.setText("Ter");
        ter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terActionPerformed(evt);
            }
        });

        qua.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        qua.setForeground(new java.awt.Color(255, 255, 255));
        qua.setText("Qua");
        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });

        qui.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        qui.setForeground(new java.awt.Color(255, 255, 255));
        qui.setText("Qui");
        qui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiActionPerformed(evt);
            }
        });

        sex.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        sex.setForeground(new java.awt.Color(255, 255, 255));
        sex.setText("Sex");
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });

        sab.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        sab.setForeground(new java.awt.Color(255, 255, 255));
        sab.setText("Sab");
        sab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabActionPerformed(evt);
            }
        });

        dom.setFont(new java.awt.Font("Sitka Banner", 0, 12)); // NOI18N
        dom.setForeground(new java.awt.Color(255, 255, 255));
        dom.setText("Dom");
        dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pessoa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qui)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dom))
                                    .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seg)
                    .addComponent(ter)
                    .addComponent(qua)
                    .addComponent(qui)
                    .addComponent(sex)
                    .addComponent(sab)
                    .addComponent(dom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensagemActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if(editando){
            Csv.sRemove(dados, indexMsg, caminho);
            editando = false;
        }
        Csv.swriterCSV(Home.caminho,geraArray());
        Telas.setMsg.dispose();
        Telas.sucesso.setVisible(true);
        Home.adm.refresh = true;
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        Telas.setMsg.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void segActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segActionPerformed

    private void terActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terActionPerformed

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaActionPerformed

    private void quiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void sabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabActionPerformed

    private void domActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domActionPerformed

    private String[] geraArray(){
        String[] dados = new String[4];
        dados[0] = mensagem.getText();
        dados[1] = pessoa.getText();
        if(UtilidadesHorario.scheckValid(hora.getText() + ":" + minuto.getText())){
        dados[2] = hora.getText() + ":" + minuto.getText();
        }else{
            dados[2] = "-1:-1";
        }
        dados[3] = buildStringDayWeek();
        return dados;
    }
    
    
    public String[] getGeraArray(){
        return geraArray();
    }
    public int getMessageId() throws IOException, CsvException{
        indexMsg = Telas.select.selectMessage();
        return indexMsg;
    }
    public void getDados(){
        dados = Csv.sreaderCsv(caminho);
        dados = UtillMsg.ordenarPorHorario(dados);
    }
    
    public void setEditData(){
        getDados();
        String aux = String.valueOf(UtilidadesHorario.formataHorario(dados.get(indexMsg)[posHorario])[0]);
        if(Integer.parseInt(aux) < 9 && Integer.parseInt(aux) > -1) aux = "0" + aux;
        mensagem.setText(dados.get(indexMsg)[posMensagem]);
        pessoa.setText(dados.get(indexMsg)[posPessoa]);
        hora.setText(aux);
        aux = String.valueOf(UtilidadesHorario.formataHorario(dados.get(indexMsg)[posHorario])[1]);
        if(Integer.parseInt(aux) < 9 && Integer.parseInt(aux) > -1) aux = "0" + aux;
        minuto.setText(aux);
        decodeHash();
    }
    
    public void decodeHash(){
        String hash = dados.get(indexMsg)[posWeek];
        String[] hashFatiado = hash.split("");
        if(!hashFatiado[0].equals("0")) {
            seg.setSelected(true);
        }else{
            seg.setSelected(false);
        }
        
        if(!hashFatiado[1].equals("0")) {
            ter.setSelected(true);
        }else{
            ter.setSelected(false);
        }
        
        if(!hashFatiado[2].equals("0")) {
            qua.setSelected(true);
        }else{
            qua.setSelected(false);
        }
        
        if(!hashFatiado[3].equals("0")){
            qui.setSelected(true);
        }else{
            qui.setSelected(false);
        }
        
        if(!hashFatiado[4].equals("0")) {
            sex.setSelected(true);
        }else{
            sex.setSelected(false);
        }
        
        if(!hashFatiado[5].equals("0")){
            sab.setSelected(true);
        }else{
            sab.setSelected(false);
        }
        
        if(!hashFatiado[6].equals("0")) {
            dom.setSelected(true);
        }else{
            dom.setSelected(false);
        }
    }
    private String buildStringDayWeek(){
        String build = "";
        if(seg.isSelected()){
            build = build + "1";
        }else{
            build = build + "0";
        }
        if(ter.isSelected()){
            build = build + "2";
        }else{
            build = build + "0";
        }
        if(qua.isSelected()){
            build = build + "3";
        }else{
            build = build + "0";
        }
        if(qui.isSelected()){
            build = build + "4";
        }else{
            build = build + "0";
        }
        if(sex.isSelected()){
            build = build + "5";
        }else{
            build = build + "0";
        }
        if(sab.isSelected()){
            build = build + "6";
        }else{
            build = build + "0";
        }
        if(dom.isSelected()){
            build = build + "7";
        }else{
            build = build + "0";
        }
        return build;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetMsgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetMsgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetMsgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetMsgs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetMsgs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JCheckBox dom;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mensagem;
    private javax.swing.JTextField minuto;
    private javax.swing.JTextField pessoa;
    private javax.swing.JCheckBox qua;
    private javax.swing.JCheckBox qui;
    private javax.swing.JCheckBox sab;
    private javax.swing.JCheckBox seg;
    private javax.swing.JCheckBox sex;
    private javax.swing.JCheckBox ter;
    // End of variables declaration//GEN-END:variables
}
